// @flow
import React from 'react';
import { Caption } from 'react-native-paper';

type ErrorType = 'required' | 'apiError' | 'error' | string;

type InputType = 'email' | 'mobileNumber' | 'zipCode' | 'otp';

export function getErrorMessage(
  type: ErrorType = 'required',
  inputName: ?InputType,
): string {
  const genericMessage = 'This input is invalid.';

  switch (type) {
    case 'required':
      return 'This input is required.';

    case 'apiError':
      return 'Something went wrong! Please try again.';

    case 'error': {
      const messages = {
        email: 'This is an invalid email.',
        mobileNumber: 'This is an invalid mobile number.',
        zipCode: 'This is an invalid ZIP code.',
        otp: 'This is an invalid verification code.',
      };

      return inputName ? messages[inputName] : genericMessage;
    }

    default:
      return genericMessage;
  }
}

export type ContentType = {
  dropdown: string,
  inputNames: {
    name: string,
    mobileNumber: string,
    dob: string,
    gender: string,
    address: string,
    email: string,
    avatar: string,
    profession: string,
    industry: string,
    education: string,
    experience: string,
  },
  setup: {
    intro: React$Node | string,
    tagline: React$Node | string,
    primaryCTA: string,
    colophon: string,
    madeInIndia: string,
    optionsHeading: string,
    optionsLabel: string,
    employeeCTA: string,
    employerCTA: string,
  },
  languages: {
    title: string,
  },
  signUp: {
    heading: string,
    subheading: string,
    getStarted: string,
    disclaimer: Function,
    alreadyRegistered: string,
    login: string,
    asGuest: string,
  },
  login: {
    heading: string,
    subheading: string,
    requestOtp: string,
    noAccount: string,
    register: string,
    asGuest: string,
  },
  courses: {
    congratulations: string,
    stars: string,
    disclaimerSuccess: string,
    continue: string,
    disclaimerSuccess: React$Node,
    continue: string,
    oops: string,
    betterLuck: string,
    disclaimerFailure: string,
    retry: string,
  },
  editProfile: {
    appbarTitle: string,
    steps: Function,
    format: string,
    save: string,
  },
};

type GetAppContentType = {
  ENGLISH: ContentType,
  HINDI: ContentType,
};

export function getAppContent(): GetAppContentType {
  return {
    HINDI: {
      dropdown: 'एक विकल्प चुनें',
      inputNames: {
        name: 'नाम',
        mobileNumber: 'मोबाइल नंबर',
        dob: 'जनम तिथि',
        gender: 'लिंग',
        address: 'पता',
        email: 'ईमेल',
        avatar: 'प्रोफ़ाइल चित्र अपलोड करें',
        profession: 'पेशा',
        industry: 'उद्योग',
        education: 'शिक्षा',
        experience: 'कार्य अनुभव',
      },
      setup: {
        intro: 'खोजें एक आदर्श रोज़गार',
        tagline: 'पाएं अपने सपनों की नौकरी मेरा रोज़गार ऐप के साथ',
        primaryCTA: 'शुरू करें',
        colophon: 'SIGMA द्वारा संचालित',
        madeInIndia: 'भारत में बना',
        optionsHeading: 'आप क्या ढूंढ रहे हैं?',
        optionsLabel: 'जारी रखने के लिए एक विकल्प चुनें',
        employeeCTA: 'नौकरी ढूंढो',
        employerCTA: 'भर्ती शुरू करें',
      },
      languages: {
        title: 'भाषा चुनें / Select language',
      },
      signUp: {
        heading: 'साइन अप करें',
        subheading: 'जारी रखने के लिए नीचे अपनी जानकारी दर्ज करें',
        getStarted: 'शुरू करें',
        disclaimer: (theme) => (
          <Caption
            style={{ color: theme.colors.placeholder, letterSpacing: 0 }}>
            <Caption style={{ color: theme.colors.text, letterSpacing: 0 }}>
              शुरू करें
            </Caption>{' '}
            पर क्लिक करके, आप हमारे{' '}
            <Caption style={{ color: theme.colors.primary, letterSpacing: 0 }}>
              नियम, शर्तों
            </Caption>{' '}
            व{' '}
            <Caption style={{ color: theme.colors.primary, letterSpacing: 0 }}>
              प्राइवेसी पॉलिसी
            </Caption>{' '}
            से सहमत होते हैंI
          </Caption>
        ),
        alreadyRegistered: 'क्या आप पहले से रजिस्टर्ड है?',
        login: 'लॉगिन करें',
        asGuest: 'अतिथि के रूप में जारी रखें',
      },
      login: {
        heading: 'लॉगिन करें',
        subheading: 'हम आपको इस मोबाइल नंबर पर 6 अंकों का ओटीपी भेजेंगे।',
        requestOtp: 'रिक्वेस्ट ओटीपी',
        noAccount: 'क्या आपका अकाउंट नहीं है?',
        register: 'रजिस्टर करें',
        asGuest: 'अतिथि के रूप में जारी रखें',
      },
      courses: {
        congratulations: 'बधाई हो!',
        stars: 'आपके द्वारा एकत्र किए गए सितारे',
        disclaimerSuccess: (
          <>
            एक बार जब आप 6 स्टार जमा कर लेते हैं, तो आपकी प्रोफ़ाइल पर{'\n'}एक
            बैज दिखाई देगा।
          </>
        ),
        continue: 'अगले वीडियो के लिए जारी रखें',
        oops: 'उफ़',
        betterLuck: 'अगली बार किस्मत तुम्हारा साथ देगी!',
        disclaimerFailure: 'पास होने के लिए आपको कम से कम 50% अंक लाने होंगे।',
        retry: 'पुन: प्रयास करें',
      },
      editProfile: {
        appbarTitle: 'अपनी प्रोफाइल पूरी करें',
        steps: (step) => `स्टेप ${step}/3`,
        format: 'अनुमत प्रारूप .jpeg, .jpg या .png हैं।',
        save: 'सेव',
      },
    },
    ENGLISH: {
      dropdown: 'Choose an option',
      inputNames: {
        name: 'Name',
        mobileNumber: 'Mobile Number',
        dob: 'Date of Birth',
        gender: 'Gender',
        address: 'Address',
        email: 'Email',
        avatar: 'Upload profile picture',
        profession: 'Profession',
        industry: 'Industry',
        education: 'Education',
        experience: 'Experience',
      },
      setup: {
        intro: <>Find a Perfect{'\n'}Job Match.</>,
        tagline: <>Find your dream job with Mera Rozgaar app</>,
        primaryCTA: "Let's get started",
        colophon: 'Powered by SIGMA',
        madeInIndia: 'Made in India',
        optionsHeading: 'What are you looking for?',
        optionsLabel: 'Select an option to continue',
        employeeCTA: 'Find a job',
        employerCTA: 'Start hiring',
      },
      languages: {
        title: 'भाषा चुनें / Select language',
      },
      signUp: {
        heading: 'Sign up',
        subheading: 'Enter your information below to continue.',
        getStarted: 'Get started',
        disclaimer: (theme) => (
          <Caption
            style={{ color: theme.colors.placeholder, letterSpacing: 0 }}>
            By clicking{' '}
            <Caption style={{ color: theme.colors.text, letterSpacing: 0 }}>
              Get started
            </Caption>
            , you agree to our{' '}
            <Caption style={{ color: theme.colors.primary, letterSpacing: 0 }}>
              Terms & Conditions
            </Caption>
            {'\n'}
            and{' '}
            <Caption style={{ color: theme.colors.primary, letterSpacing: 0 }}>
              Privacy Policy
            </Caption>
            .
          </Caption>
        ),
        alreadyRegistered: 'Already registered?',
        login: 'Login now',
        asGuest: 'Continue as Guest',
      },
      login: {
        heading: 'Login to continue',
        subheading: 'We will send you a 6 digit OTP on this mobile number.',
        requestOtp: 'Request OTP',
        noAccount: "Don't have an account?",
        register: 'Register now',
        asGuest: 'Continue as Guest',
      },
      courses: {
        congratulations: 'Congratulations!',
        stars: "Stars you've collected",
        disclaimerSuccess: (
          <>
            Once you collect 6 stars, a badge will appear{'\n'}on your profile.
          </>
        ),
        continue: 'Continue to next video',
        oops: 'Oops!',
        betterLuck: 'Better luck next time!',
        disclaimerFailure: 'You need to score a minimum of 50% to pass.',
        retry: 'Try again',
      },
      editProfile: {
        appbarTitle: 'Complete your profile',
        steps: (s) => `Step ${s}/3`,
        format: 'Allowed formats are .jpeg, .jpg or .png.',
        save: 'Save',
      },
    },
  };
}

const skills = [
  // 'Aerospace and Aviation',
  // 'Agriculture and Allied',
  // 'Apparel / Textile',
  // 'Automotive',
  // 'Banking, Financial Services and Insurance',
  // 'Beauty & Wellness',
  // 'Biotechnology',
  // 'Capital Goods',
  // 'Cement',
  // 'Chemicals',
  // 'Construction',
  // 'Consumer Durables',
  // 'Domestic Workers',
  // 'E-Commerce',
  // 'Education and Training',
  // 'Electronics',
  // 'Engineering',
  // 'Food Processing',
  // 'Furniture & Fittings',
  // 'Gems & Jewellery',
  // 'Handicrafts and Carpet',
  // 'Healthcare',
  // 'Hospitality and Tourism',
  // 'Information Technology',
  // 'Infrastructure',
  // 'Instrumentation',
  // 'Iron and Steel',
  // 'Leather',
  // 'Life Sciences',
  // 'Logistics',
  // 'Management',
  // 'Manufacturing',
  // 'Media & Entertainment',
  // 'Medical Devices',
  // 'Metals and Mining',
  // 'MSME',
  // 'Oil and Gas',
  // 'Paints and Coatings',
  // 'Pharmaceuticals',
  // 'Plumbing',
  // 'Ports',
  // 'Power',
  // 'Railways',
  // 'Real Estate',
  // 'Renewable Energy and Green Jobs',
  // 'Retail',
  // 'Roads',
  // 'Rubber',
  // 'Science and Technology',
  // 'Services',
  // 'Sports',
  // 'Telecommunications',
  // 'एयरोस्पेस और एविएशन',
  // 'कृषि और संबद्ध',
  // 'वस्त्र',
  // 'ऑटोमोटिव',
  // 'बैंकिंग, वित्तीय सेवाएं और बीमा',
  // 'सौंदर्य और कल्याण',
  // 'जैव प्रौद्योगिकी',
  // 'पूंजीगत सामान',
  // 'सीमेंट',
  // 'रसायन',
  // 'निर्माण',
  // 'कंज्यूमर ड्यूरेबल्स',
  // 'घरेलू कामगार',
  // 'ई-कॉमर्स',
  // 'शिक्षा और प्रशिक्षण',
  // 'इलेक्ट्रॉनिक्स',
  // 'इंजीनियरिंग',
  // 'खाद्य प्रसंस्करण',
  // 'फर्नीचर और फिटिंग',
  // 'रत्न और आभूषण',
  // 'हस्तशिल्प और कालीन',
  // 'स्वास्थ्य देखभाल',
  // 'आतिथ्य और पर्यटन',
  // 'सूचना प्रौद्योगिकी',
  // 'बुनियादी ढांचा',
  // 'इंस्ट्रुमेंटेशन',
  // 'लोहा और इस्पात',
  // 'चमड़ा',
  // 'जीवन विज्ञान',
  // 'रसद',
  // 'लॉजिस्टिक्स',
  // 'विनिर्माण',
  // 'मीडिया और मनोरंजन',
  // 'चिकित्सा उपकरण',
  // 'धातु और खनन',
  // 'सूक्ष्म, लघु व मध्यम उद्योग',
  // 'तेल और गैस',
  // 'पेंट और कोटिंग्स',
  // 'फार्मास्यूटिकल्स',
  // 'प्लंबिंग',
  // 'बंदरगाह',
  // 'पावर',
  // 'रेलवे',
  // 'रियल एस्टेट',
  // 'अक्षय ऊर्जा और हरित नौकरियां',
  // 'खुदरा',
  // 'सड़कें',
  // 'रबड़',
  // 'विज्ञान और प्रौद्योगिकी',
  // 'सर्विसेज',
  // 'खेल',
  // 'दूरसंचार',
  // 'AC Technician',
  // 'Accounts / Finance',
  // 'Acupressure therapist',
  // 'Admin / Office Assistant',
  // 'Aerodynamics Engineer',
  // 'Aircraft Maintenance',
  // 'Airline Cabin Crew',
  // 'Airline Cargo Assistant',
  // 'Airline High Lift Truck Operator',
  // 'Airline Security Staff',
  // 'App Developer',
  // 'Aquaculture/ Fish farm',
  // 'Baby/Child caretaker',
  // 'Back Office',
  // 'Beautician / Hair Stylist',
  // 'Business Development',
  // 'Caregiver for mother & newborn',
  // 'Caretaker for disabled/ elderly',
  // 'Carpenter',
  // 'Chemical Engineer',
  // 'Civil Engineer',
  // 'Cold Store',
  // 'Computer / Data Entry Operator / COPA',
  // 'Computer Engineer',
  // 'Content Writing',
  // 'Cook / Chef / Baker',
  // 'Corporate Trainer',
  // 'Counsellor',
  // 'Dairy farm',
  // 'Delivery Person',
  // 'Digital Marketing / Online Marketing',
  // 'Doctors',
  // 'Draughtsman',
  // 'Driver',
  // 'DTP Operator / Printer',
  // 'Electrical Engineer',
  // 'Electrician / Wireman',
  // 'Electronic Engineer',
  // 'Engineer (Other)',
  // 'Farmer/ Cultivator',
  // 'Fashion Designer',
  // 'Fitness Trainer',
  // 'Florist',
  // 'Foreman',
  // 'Foundry',
  // 'Gardener/ Nursery Worker',
  // 'Graphic Designer',
  // 'Hand Embroiderer /Weaver',
  // 'Hardware & Network Engineer',
  // 'Hospitality / Hotel Management',
  // 'Hotel / Restaurant Staff',
  // 'Housekeeping',
  // 'Human resources',
  // 'Instrument Mechanic',
  // 'Insurance agent',
  // 'Interior Designer',
  // 'IT Support',
  // 'Lab Technician',
  // 'Labour / Worker',
  // 'Legal',
  // 'Logistics/Operations',
  // 'Machine Operator',
  // 'Maid',
  // 'Marketing',
  // 'Mason',
  // 'Mechanic',
  // 'Mechanical Engineer',
  // 'Medical (Other)',
  // 'Mobile Technician',
  // 'Mutual fund agent',
  // 'Nurse',
  // 'Office Help / Peon',
  // 'Operations',
  // 'Pack house',
  // 'Painter',
  // 'Pharmacist',
  // 'Plumber',
  // 'Poultry Farm',
  // 'Receptionist / Front Office Desk',
  // 'Refrigerator Technician',
  // 'Retail',
  // 'Sales (Field Work)',
  // 'Scaffolder',
  // 'Security Guard',
  // 'Software / Web Developer',
  // 'Solar Engineer',
  // 'Spa therapist',
  // 'Storekeeper',
  // 'Supervisor',
  // 'Tailor / Cutting Master',
  // 'Teacher',
  // 'Technician',
  // 'Telecaller / BPO',
  // 'Tool and Die Maker',
  // 'Turner-Fitter',
  // 'Video Editor',
  // 'Ward Helper',
  // 'Warehouse',
  // 'Welder',
  // 'Yoga trainer',
  // 'एसी तकनीशियन',
  // 'लेखा / वित्त',
  // 'एक्यूप्रेशर थेरेपिस्ट',
  // 'व्यवस्थापक / कार्यालय सहायक',
  // 'वायुगतिकी इंजीनियर',
  // 'विमान रखरखाव',
  // 'एयरलाइन केबिन क्रू',
  // 'एयरलाइन कार्गो सहायक',
  // 'एयरलाइन हाई लिफ्ट ट्रक ऑपरेटर',
  // 'एयरलाइन सुरक्षा कर्मचारी',
  // 'ऐप डेवलपर',
  // 'जलीय कृषि/मछली फार्म',
  // 'बेबी / चाइल्ड केयरटेकर',
  // 'बैक कार्यालय',
  // 'ब्यूटीशियन / हेयर स्टाइलिस्ट',
  // 'व्यापार विकास',
  // 'माँ और नवजात शिशु की देखभाल',
  // 'विकलांग/बुजुर्गों की देखभाल',
  // 'कारपेंटर',
  // 'रासायनिक इंजीनियर',
  // 'सिविल इंजीनियर',
  // 'कोल्ड स्टोर',
  // 'कंप्यूटर / डाटा एंट्री ऑपरेटर / सीओपीए',
  // 'कंप्यूटर इंजीनियर',
  // 'कंटेंट लेखन',
  // 'रसोइया / बावर्ची / बेकर',
  // 'कॉर्पोरेट ट्रेनर',
  // 'काउंसलर',
  // 'गोशाला',
  // 'डिलिवरी करने वाला व्यक्ति',
  // 'डिजिटल मार्केटिंग / ऑनलाइन मार्केटिंग',
  // 'डॉक्टर',
  // 'नक़्शानवीस',
  // 'ड्राइवर',
  // 'डीटीपी ऑपरेटर / प्रिंटर',
  // 'विद्युत इंजीनियर',
  // 'इलेक्ट्रीशियन / वायरमैन',
  // 'इलेक्ट्रॉनिक इंजीनियर',
  // 'इंजीनियर (अन्य)',
  // 'किसान',
  // 'फैशन डिजाइनर',
  // 'फिटनेस ट्रेनर',
  // 'फूलवाला',
  // 'फोरमैन/ पंचों का सरदार',
  // 'फाउंड्री',
  // 'माली/नर्सरी कार्यकर्ता',
  // 'ग्राफिक डिजाइनर',
  // 'हाथ से कढ़ाई करने वाला/ बुनकर',
  // 'हार्डवेयर और नेटवर्क इंजीनियर',
  // 'हॉस्पिटैलिटी / होटल प्रबंधन',
  // 'होटल / रेस्टोरेंट कर्मचारी',
  // 'घर का रख रखाव',
  // 'मानव संसाधन',
  // 'यंत्र मैकेनिक',
  // 'बीमा एजेंट',
  // 'इंटीरियर डिज़ाइनर',
  // 'आईटी समर्थन',
  // 'प्रयोगशाला तकनीशियन',
  // 'श्रमिक / कार्यकर्ता',
  // 'कानूनी',
  // 'लोजिस्टिक्स/ संचालन',
  // 'मशीन आपरेटर',
  // 'मेड (सेविका )',
  // 'विपणन',
  // 'मिस्त्री',
  // 'मैकेनिक',
  // 'यांत्रिकी अभियंता',
  // 'चिकित्सा (अन्य)',
  // 'मोबाइल तकनीशियन',
  // 'म्यूचुअल फंड एजेंट',
  // 'नर्स',
  // 'कार्यालय सहायता / चपरासी',
  // 'संचालन',
  // 'पैक हाउस',
  // 'पेंटर',
  // 'फार्मेसिस्ट',
  // 'प्लंबर/ नलकार',
  // 'मुर्गीपालन फार्म',
  // 'रिसेप्शनिस्ट / फ्रंट ऑफिस डेस्क',
  // 'रेफ्रिजरेटर तकनीशियन',
  // 'खुदरा',
  // 'बिक्री (क्षेत्रीय कार्य)',
  // 'मचान',
  // 'सुरक्षा गार्ड',
  // 'सॉफ्टवेयर / वेब डेवलपर',
  // 'सौर अभियंता',
  // 'स्पा थेरेपिस्ट',
  // 'दुकानदार',
  // 'पर्यवेक्षक',
  // 'दर्जी / कटिंग मास्टर',
  // 'अध्यापक',
  // 'तकनीशियन',
  // 'टेलीकॉलर / बीपीओ',
  // 'टूल एंड डाई मेकर',
  // 'टर्नर-फिटर',
  // 'वीडियो संपादक/ वीडियो एडीटर',
  // 'वार्ड हेल्पर',
  // 'गोदाम',
  // 'वेल्डर',
  // 'योगा ट्रेनर',

  // 'Primary',
  // '10th pass',
  // '12th pass',
  // 'Diploma',
  // 'Graduate',
  // 'Postgraduate',

  // 'प्राइमरी',
  // '10 वीं पास',
  // '12 वीं पास',
  // 'डिप्लोमा',
  // 'ग्रेजुएट',
  // 'पोस्ट ग्रेजुएट',
  '100 से कम',
  '100-1000',
  '1000 से ऊपर',
].reduce(
  (a, c, i) => `${a} (${i + 1}, "${c}", "HINDI", "COMPANY_SIZE_TYPE"),`,
  'INSERT INTO types (display_order, label, language, type) VALUES',
);

console.log(skills);
